plugins {
    id 'com.android.application'
}

android {
    namespace 'com.rasputin.accessibilitycopyhelper'
    compileSdk 36

    defaultConfig {
        applicationId 'com.rasputin.accessibilitycopyhelper'
        minSdk 26
        targetSdk 36
        versionCode 1
        versionName '1.0.0-linkv1'
    }
}
